### PR TITLE
Changed the UI of the feedback section

### PR DESCRIPTION
**Pull request by shriyadindi**
Issue no. : #1179 
I've changed the entire UI of the feedback section by modifying numerous features.
Screenshot (391)
Screenshot (392)

### CODE REVIEW

**Comment by shriyadindi** [comment]
@iamrahulmahato I've resolved the merge conflicts.
issue no: #1198

**Comment by iamrahulmahato** [comment]
conflict is not resolved

**Comment by shriyadindi** [comment]
> conflict is not resolved

I'll resolve it.

**Comment by shriyadindi** [comment]
@iamrahulmahato I've resolved the merge conflicts

**Pull request merged**
