### PR TITLE
Created a virtual pet game

### PR DESCRIPTION
**Pull request by Ishika-Gupta06**
1**.Movement Animation:**
The turtle moves from the right side to the left side of the screen in a linear motion.
2.**Fixed Position for Images:**
The cat-mouse and dog images are fixed in the bottom-right and bottom-left corners, respectively, for consistent visibility.
3.**Real-Time Status Updates:**
The pet's status (Hunger, Boredom, Health, Tiredness) updates every second and reflects the player's interactions.
4.**Interactive Buttons:**
Buttons allow players to perform actions such as feeding the pet, playing with it, giving medicine, and putting it to bed.
5.**Visual Feedback:**
Animations for different pet states (hungry, bored, sick, tired) are applied based on the pet's status, enhancing visual engagement.
6.**Responsive Design:**
The layout is designed to be responsive, ensuring all elements are visible without scrolling, creating a user-friendly experience.
These features make your virtual pet game engaging and interactive!
 
_task #418 completed_

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
there is a conflict resolve it

**Comment by Ishika-Gupta06** [comment]
@iamrahulmahato conflict has been resolved

**Comment by iamrahulmahato** [comment]
solved the conflict. And then try to push.

**Comment by Ishika-Gupta06** [comment]
@iamrahulmahato done

**Pull request merged**
