### PR TITLE
Added whack a mole game #358

### PR DESCRIPTION
**Pull request by Abankita**
@iamrahulmahato As mentioned in issue number #358 , I have added a Whack a mole game. Please review the pr. Any feedback and suggestions are welcomed.
Screenshot (69)~2
Screenshot (70)~2

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
there is a conflict resolve it

**Comment by Abankita** [comment]
@iamrahulmahato I have resolved the conflicts

**Comment by Abankita** [comment]
@iamrahulmahato I've resolved the conflict

**Comment by Abankita** [comment]
@iamrahulmahato I've resolved the conflict.And someone else has made the same game. Please check!

**Comment by Abankita** [comment]
@iamrahulmahato Done with resolving the conflicts. Please review.

**Comment by Abankita** [comment]
@iamrahulmahato please check now. Thanks in advance!

**Comment by iamrahulmahato** [comment]
bro its not resolve

**Comment by Abankita** [comment]
@iamrahulmahato Done! A suggestion- Please review the earlier PRs as merging the latest PRs are conflicting some previous pull requests. I hope you don't mind. Thank you so much for giving this learning experiences!

**Pull request merged**
