### PR TITLE
Add space invader

### LINKED ISSUE #389: Add Space Invaders game
I want to add a space invader game

image

### PR DESCRIPTION
**Pull request by souvikpramanikgit**
Fix #389 , Add Space Invader Game.

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
there is a conflict resolve it

**Comment by souvikpramanikgit** [comment]
This branch has no conflicts with the base branch @iamrahulmahato .

**Comment by iamrahulmahato** [comment]
not resolve

**Comment by souvikpramanikgit** [comment]
Solve it 

image

**Pull request merged**
