### PR TITLE
Mismanagement of Footer Resolve

### PR DESCRIPTION
**Pull request by VanshGarg06**
The Footer was misaligned and the elements are also misaligned the styling was not good and not all the elements are aligned as per previous layout as the original Layout was actually nice. Noe the User Interface has been enhanced which is important for any website. In return, User Experience also enhanced. 

Closes:
#2160 Mismanagement of Footer

**Screenshots**
image
image

**Additional Context**
I know that their might be merge conflicts regarding the harder logo but i will handle the same later in another PR but please merge this for now.

### CODE REVIEW

**Comment by VanshGarg06** [comment]
I think the conflicts are not necessary i will do the changes of header don't worry.

**Comment by iamrahulmahato** [comment]
@VanshGarg06 reslove the conflict

**Comment by iamrahulmahato** [comment]
@VanshGarg06 resolve the conflict

**Comment by iamrahulmahato** [comment]
@VanshGarg06  Tomorrow, the program will come to an end so resolved the conflict.

**Pull request closed without merging**
