### PR TITLE
Issue #68  Community-Driven Forum for Web Development Discussions

### PR DESCRIPTION
**Pull request by meghanakn473**
This PR introduces a community-driven forum feature, allowing users to ask questions, share knowledge, and seek help on web development topics. The forum includes a user-friendly interface for submitting questions and answering them, fostering engagement and collaboration among developers. Dynamic updates ensure real-time visibility of new posts, enhancing the overall user experience. This feature aims to create an interactive platform for developers to connect and support one another in their web development journeys.

Proof:

Screenshot (140)

### CODE REVIEW

**Comment by meghanakn473** [comment]
@iamrahulmahato kindly review my pr and allow to merge

**Comment by iamrahulmahato** [comment]
Put all of your files inside a folder and move it to the project section.

**Comment by meghanakn473** [comment]
@iamrahulmahato hey can I know wt is the invalid label about....while it passed all the checks n has no merge conflicts

**Comment by meghanakn473** [comment]
> Put all of your files inside a folder and move it to the project section.

@iamrahulmahato How do i do this please guide me

**Comment by meghanakn473** [comment]
> Put all of your files inside a folder and move it to the project section.

@iamrahulmahato can u please justify?

**Comment by iamrahulmahato** [comment]
Web capture_5-10-2024_93513_github com
Put all of your files and folders inside a folder, like community, and then move that file to the project folder.
Web capture_5-10-2024_93728_github com

**Comment by meghanakn473** [comment]
@iamrahulmahato can u please assign me the level 3 label and allow to merge?

**Comment by iamrahulmahato** [comment]
I labeled you as a question because I need further clarification as your file structure does not fit in my repo. That is why I am telling you to put all of your files in the project section in my repo

**Comment by iamrahulmahato** [comment]
now good to go

**Comment by iamrahulmahato** [comment]
What is your issue no?

**Comment by iamrahulmahato** [comment]
close #68

**Pull request merged**
