### PR TITLE
Added WordSearch Game

### PR DESCRIPTION
**Pull request by jvkousthub**
Built using HTML, CSS, JS

HTML Structure (index.html):

Created a new HTML structure for the Word Search Game.
Added a container for the game elements, including the grid and the list of words to find.
Included a reset button to restart the game.
Linked the necessary CSS and JavaScript files for styling and functionality.
CSS Styling (styles.css):

Added styles for the Word Search Game container, grid, and word list.
Styled the reset button for better user interaction.
Ensured responsive design for different screen sizes.
JavaScript Functionality (script.js):

Implemented the logic for generating the word search grid.
Added functionality to highlight words when found.
Included a reset function to restart the game

image
image

Closes: #540

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by jvkousthub** [comment]
image


@iamrahulmahato @serenagomez060203  Please look into it

**Comment by jvkousthub** [comment]
> mention the issue no

Closes : #540

**Comment by iamrahulmahato** [comment]
> image
> 
> @iamrahulmahato @serenagomez060203 Please look into it

mention the issue no of this

**Comment by jvkousthub** [comment]
> > image
> > @iamrahulmahato @serenagomez060203 Please look into it
> 
> mention the issue no of this

Issue No : #540

**Comment by iamrahulmahato** [comment]
@jvkousthub bhai hacktoberfest wala pucha jisme message a rha hain

**Comment by iamrahulmahato** [comment]
> image
> 
> @iamrahulmahato @serenagomez060203 Please look into it

.

**Comment by jvkousthub** [comment]
image

This issue itself

**Comment by jvkousthub** [comment]
> image
> 
> This issue itself

Is this what is wanted or something else 
sorry if i am wrong

**Comment by iamrahulmahato** [comment]
done

**Comment by jvkousthub** [comment]
> image
> 
> @iamrahulmahato @serenagomez060203 Please look into it

@iamrahulmahato In hacktober fest website it is still like this

**Pull request merged**
