### PR TITLE
Add Note Taking website

### LINKED ISSUE #341: Add New Project - Notes taking app
Hi,

I want to add a notes taking app which is looks like this
image

### PR DESCRIPTION
**Pull request by souvikpramanikgit**
Fix #341 , I add the Note Taking Website with code and image.

### CODE REVIEW

**Comment by souvikpramanikgit** [comment]
image

**Comment by iamrahulmahato** [comment]
there is a conflict resolve it

**Comment by souvikpramanikgit** [comment]
ok, wait for some time, i will solve it.

**Comment by souvikpramanikgit** [comment]
I resolve it @iamrahulmahato , check this  https://github.com/iamrahulmahato/master-web-development/pull/438

**Pull request closed without merging**
