### PR TITLE
Add Star rating widget done ! #1458

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature Star rating widget - #1458
Done -

https://github.com/user-attachments/assets/b374ea3d-8f55-4a5e-acbc-917007018fa9

Screenshot 2024-10-28 203350

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato

**Comment by iamrahulmahato** [comment]
@Subhajit-2023-44 there is a conflict

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 there is a conflict

@iamrahulmahato done

**Comment by iamrahulmahato** [comment]
@Subhajit-2023-44 not solved

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 not solved

@iamrahulmahato done 

image

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato please give me level 2

**Pull request merged**
