### PR TITLE
Feat: Added Healthy Meal Planner

### PR DESCRIPTION
**Pull request by shivisingh25**
@iamrahulmahato  Hey, I've created PR for issue : #1295. 
image
image
image

### CODE REVIEW

**Comment by shivisingh25** [comment]
@iamrahulmahato Please review this issue : #1295

**Comment by shivisingh25** [comment]
@iamrahulmahato ,I've create PR.Please merge it.

**Comment by shivisingh25** [comment]
@iamrahulmahato ,There is no any conflict showing in PR.Please check it

**Comment by iamrahulmahato** [comment]
Web capture_19-10-2024_10229_github com
it showing

**Comment by shivisingh25** [comment]
image
@iamrahulmahato Please check it

**Comment by iamrahulmahato** [comment]
Web capture_19-10-2024_152117_github com
Web capture_19-10-2024_152031_github com
Web capture_19-10-2024_152010_github com
@shivisingh25     Actually this are the conflict you can directly solve it github also

**Comment by shivisingh25** [comment]
@iamrahulmahato Done.Have a look on it.

**Pull request merged**
