### PR TITLE
Added a Hangman Game Project

### PR DESCRIPTION
**Pull request by rimmon1234**
Hangman is a word game where one player guesses letters to solve a word chosen by another player. If the player guessing makes a wrong guess, the other player draws a part of a person being hanged. The game is over when the person being hanged is complete. 
Screenshot 2024-10-02 203259

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by Tapabrata-Goswami** [comment]
@rimmon1234 mentioned the issue number

**Comment by rimmon1234** [comment]
Issue No #222

**Comment by Tapabrata-Goswami** [comment]
@rimmon1234 It's merged. Thanks for your **contribution**.

**Comment by rimmon1234** [comment]
Hello I Am a bit concerned that my this contribution or pr is not shown in the gssoc leaderboard

**Comment by rimmon1234** [comment]
Please Give The Necessary Labels For Gssoc @iamrahulmahato @Tapabrata-Goswami

**Pull request merged**
