### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Dipanita45**
Update the icon , button container color, add more transition
Change the project card section
And more css properties
Thank you for the chance and please label
#850

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
mention issue no?
and resolve the conflict

**Comment by Dipanita45** [comment]
#850

**Comment by Dipanita45** [comment]
I had resolve the conflicts

**Comment by Dipanita45** [comment]
I had resolve the conflicts then also not showing as resolved
Sorry for the inconvenience
Please review my pull request @iamrahulmahato  and please label me

**Comment by iamrahulmahato** [comment]
I am closing this PR because I believe there are some problems. Could you please create a new one?

**Comment by Dipanita45** [comment]
I am creating a new pr

**Pull request closed without merging**
