### PR TITLE
Add Mini Calender

### PR DESCRIPTION
**Pull request by amanver45**
issue #503 

https://github.com/user-attachments/assets/977c5a96-aaf6-489f-8fa9-9a747aba7eed

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
there is a conflict

**Comment by amanver45** [comment]
@iamrahulmahato  conflict is removed

**Comment by amanver45** [comment]
@iamrahulmahato  pls check and merge it

**Comment by amanver45** [comment]
@iamrahulmahato  conflict is removed

**Pull request closed without merging**
