### PR TITLE
POKEMON GAME

### PR DESCRIPTION
**Pull request by rajnil9**
Creating a new Pokemon Game using html , css  , js  .

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@rajnil9 mention the issue no

**Comment by rajnil9** [comment]
@iamrahulmahato issue number #2318

**Comment by rajnil9** [comment]
I have added the issue no. please check github pull request comment section

**Comment by rajnil9** [comment]
assign me this please @iamrahulmahato

**Pull request merged**
