### PR TITLE
issue of #737 solved added space huggers action game

### PR DESCRIPTION
**Pull request by Varchasavkr**
This game is made using advance engine javascript!

https://github.com/user-attachments/assets/fc40d5dc-1175-461f-b1e1-3dd0dcfa4935

Screenshot 2024-10-07 200058

Kindly merge this under #Hacktoberfest-accepted #gssoc-ext #level
Hopeful you will like it @iamrahulmahato 

Thankyou !

### CODE REVIEW

**Comment by Varchasavkr** [comment]
@iamrahulmahato kindly merge this PR 
Kindly attach the label of hacktoberfest-accepted
Gssoc-ext and level
Thankyou !!

**Comment by iamrahulmahato** [comment]
move all your files in one folder and move it to project section

**Comment by Varchasavkr** [comment]
@iamrahulmahato everything is in project folder  and everything follows folder previous structure
kindly merge this PR
Kindly attach the label of #hacktoberfest-accepted
#Gssoc-ext and #level2(as used advance engine JavaScript jsk13)
Thankyou !!

**Comment by Varchasavkr** [comment]
@iamrahulmahato can please merge this PR soon and attach appropriate labels

**Comment by iamrahulmahato** [comment]
fix #737

**Pull request merged**
