### PR TITLE
#666 issue solved- added finance-tracker

### PR DESCRIPTION
**Pull request by 05kaavya**
# Finance Tracker
>"Track,Save,Succeed"
## Description
A **Finance Tracker** is a website designed to help individuals or businesses manage their financial activities effectively. It allows users to _input, track,_ and _analyze_ their expenses, incomes, and savings over time. The application categorizes financial transactions into various types (e.g., food, rent, entertainment, utilities), helps users _set budget limits,_ and _visualizes_ spending trends through charts and graphs. With features like alerts for budget overruns, a Finance Tracker promotes better financial planning and assists users in reaching their financial goals.

## Tech Stack

- HTML
- CSS
- JAVASCRIPT

## ScreenShot
Screenshot 2024-10-08 125702

## Summary
The Finance Tracker simplifies personal or business finance management by providing an organized platform to record and categorize financial transactions. Users can track their expenses and incomes across different categories, set spending limits for each, and receive notifications when they exceed their budgets. The tool offers visual insights via charts (e.g., pie charts, bar graphs) to display spending patterns and monthly trends. It aids users in monitoring their financial health, staying within budget, and making informed financial decisions, ultimately supporting better financial discipline and goal achievement

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
conflict not solved

**Comment by 05kaavya** [comment]
Greetings sir,
I resolved the conflicts twice,but I have no idea why it is reappearing.
And now the conflict is not in the finance tracker as well.
Kindly help me out with this sir.

**Comment by iamrahulmahato** [comment]
If it is not working, close this PR, try to create a new one, attempt to merge your branch with the main branch, and then submit a PR request.
or
Identify the Conflict:
Run   git status (to see which files are in conflict)

**Comment by iamrahulmahato** [comment]
fix #666

**Pull request merged**
