### PR TITLE
Improve feedback form link of home page issue#1559

### PR DESCRIPTION
**Pull request by rahulbamnuya**
Issue : #1559
Before : 
Screenshot (268)
After :

Screenshot (280)

Uploading Master web development — Mozilla Firefox 2024-10-24 02-42-55.mp4…

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@rahulbamnuya resolve the conflict

**Comment by iamrahulmahato** [comment]
please update the fork then make a pr as there lot of bugs fixed but if you see your PR, they are still there

**Review by rahulbamnuya — COMMENTED** [review]
update css

**Comment by iamrahulmahato** [comment]
@rahulbamnuya Do one thing, I will close it. Then, update the fork, add your code, and create a PR.

**Pull request closed without merging**
