### PR TITLE
Slider functionality bug fixed

### PR DESCRIPTION
**Pull request by ayush-singh-26**
There was a simple mistake in the slider container and another minor issue that caused overlapping. After correcting these, the slider now functions smoothly without any overlap.

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@ayush-singh-26 resolve the conflict

**Comment by ayush-singh-26** [comment]
> @ayush-singh-26 resolve the conflict

I resolved all the conflicts

**Comment by ayush-singh-26** [comment]
> @ayush-singh-26 resolve the conflict

I resolved all the issues 
Kindly merge this pull request under hacktoberfest

**Comment by iamrahulmahato** [comment]
@ayush-singh-26 resolve the conflict and mention the issue no

**Comment by ayush-singh-26** [comment]
> @ayush-singh-26 resolve the conflict and mention the issue no
Conflicts resolved and issue no #1921

**Comment by iamrahulmahato** [comment]
@ayush-singh-26 not solved

**Comment by ayush-singh-26** [comment]
> @ayush-singh-26 not solved

is this still unsolved?

**Comment by iamrahulmahato** [comment]
> > @ayush-singh-26 resolve the conflict and mention the issue no
> > Conflicts resolved and issue no #1921
> 
> @ayush-singh-26 give the issue which i assigned you in issue tab

?

**Comment by ayush-singh-26** [comment]
Issue no #1921

**Comment by iamrahulmahato** [comment]
Web capture_30-10-2024_0726_github com
i am asking for this issue no

**Comment by ayush-singh-26** [comment]
Issue no #1834 
I think this is the issue

**Pull request merged**
