### PR TITLE
adding feature of bmi calculator#88

### PR DESCRIPTION
**Pull request by Abhishek89chauhan**
i am adding a new feature for calculating BODY MASS INDEX .Body mass index (BMI) is a measure of body fat based on height and weight that applies to adult men and women

### CODE REVIEW

**Comment by Abhishek89chauhan** [comment]
please review this

**Comment by Abhishek89chauhan** [comment]
all check have been passesd

**Comment by iamrahulmahato** [comment]
There is a conflict that resolves this and mentions the issue no

**Comment by Abhishek89chauhan** [comment]
now conflict resolved you can cheak

**Comment by Abhishek89chauhan** [comment]
my issue no. is #88

**Comment by Abhishek89chauhan** [comment]
merge this  pull  request

**Pull request merged**
