### PR TITLE
Fix issue #1504 Improved Footer Section

### PR DESCRIPTION
**Pull request by sanikamandale17**
Before
image
After 

https://github.com/user-attachments/assets/eaa13ba4-9396-4b6b-9068-50dd89cf1947

Added hover effects improved footer section........Also added more icons ......in it ...Also fix the ui
plz review it @iamrahulmahato

### CODE REVIEW

**Comment by sanikamandale17** [comment]
Plz review this

**Comment by sanikamandale17** [comment]
@iamrahulmahato I resolved the conflicts..

**Comment by sanikamandale17** [comment]
Review this I resolved conflicts

**Comment by iamrahulmahato** [comment]
man please update the fork then make a pr request

**Comment by iamrahulmahato** [comment]
conflict is still there

**Comment by iamrahulmahato** [comment]
please make a new pr after updating the fork

**Comment by sanikamandale17** [comment]
Ok

**Pull request closed without merging**
