### PR TITLE
fixed the alignment

### PR DESCRIPTION
**Pull request by shivisingh25**
issue : #1307 
@iamrahulmahato ,I've fixed the issue please review it and if possible please label this issue fixing with 'gssoc-extd' and 'hacktoberfest-accepted'
image
image

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@shivisingh25 The problem is not fixed. After a few minutes, it appears to be fixed, but then it returns to out of alignment. I believe the issue could be with the footer.

**Comment by shivisingh25** [comment]
@iamrahulmahato, I've made the changes which is required.Please review it.

**Comment by shivisingh25** [comment]
@iamrahulmahato 
https://github.com/user-attachments/assets/4b49fa04-c5d8-4599-98ee-059bb18257b4

**Comment by shivisingh25** [comment]
@iamrahulmahato please label this PR with 'hactoberfest-accepted' and 'gssoc-extd'.It's humble request.

**Comment by shivisingh25** [comment]
image
@iamrahulmahato ,You've mentioned here labels for this issue.

**Pull request merged**
