### PR TITLE
Added hangman game

### PR DESCRIPTION
**Pull request by SanikaBhalerao1345**
Developed a simple fun hangman game with different letters guessing using the hint provided.

hangman pr image
hangman pr1 img

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by sanikabhalerao241** [comment]
#398 Added hangman game.
Pls check 
Thanks

**Comment by SanikaBhalerao1345** [comment]
#398 Added hangman game.
Pls check
Thanks

**Comment by iamrahulmahato** [comment]
fix #177

**Pull request merged**
