### PR TITLE
UI Improvements and Code Cleanup

### PR DESCRIPTION
**Pull request by Kavish-Paraswar**
Updated the overall UI with minor color adjustments.
Added a hover effect to display an information card.
Improved the layout and design of the footer for better usability.
image

Changed the slider text color to black for improved visibility.
Adjusted button positions to the left for better alignment with the UI.
image

Removed a significant number of duplicates in the containers to streamline the code.
image

I would like to continue working on this issue and request to be assigned at least level 3 for the amount of work .

### CODE REVIEW

**Comment by Kavish-Paraswar** [comment]
NO confllicts with base branch
image

**Comment by iamrahulmahato** [comment]
@Kavish-Paraswar issue no?

**Comment by Kavish-Paraswar** [comment]
#1471 is the issue no

**Comment by iamrahulmahato** [comment]
@Kavish-Paraswar i am asking for issue no where i assigned you this task

**Comment by Kavish-Paraswar** [comment]
#1404 is the issue no

**Comment by Kavish-Paraswar** [comment]
Please assign level 2 for the amount of work done

**Pull request merged**
