### PR TITLE
Creating a  new Chatbot Interface 

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
# Closes : #2007

## WebDev Chatbot Interface

This project features a chat interface designed to assist users on their journey to mastering web development. It includes an interactive chatbot that provides quick access to resources, tips, and suggestions for learning HTML, CSS, JavaScript, and other web development topics.

### Features
- **Interactive Suggestions**: Get instant recommendations on topics to explore.
- **User Input**: Ask questions related to web development directly in the chat interface.
- **Feedback Collection**: Users can provide feedback on the helpfulness of the responses.
- **Responsive Design**: The interface is built to work on various devices.

# BEFORE:
image

# AFTER:
image
image

image

### CODE REVIEW

**Comment by SrijaVuppala295** [comment]
@iamrahulmahato , please review and merge , pls add level 3 label !!

**Comment by iamrahulmahato** [comment]
@SrijaVuppala295  resolve the conflict

**Comment by iamrahulmahato** [comment]
@SrijaVuppala295 not resolved

**Comment by SrijaVuppala295** [comment]
@iamrahulmahato , once please review it , I have made changes !

**Comment by SrijaVuppala295** [comment]
@iamrahulmahato , please increase my level !!

**Pull request merged**
