### PR TITLE
#708: Added New Project: Crossy Road

### PR DESCRIPTION
**Pull request by Dinkar850**
Fix: #708 

I have added a new interactive Crossy Road Game project to the collection of existing projects. 

Screenshot (1123)

Please review.

### CODE REVIEW

**Comment by Dinkar850** [comment]
@iamrahulmahato I have resolved the conflict

**Comment by Dinkar850** [comment]
@iamrahulmahato 
Also, issue #867 and its PR #924 is a duplicate so please see into it. 
Thanks!

**Comment by iamrahulmahato** [comment]
ok thank you and please resolve the conflict

**Comment by Dinkar850** [comment]
@iamrahulmahato yes actually I always resolve it and then until it is merged another project gets added and the conflict arises.. I'll do that again..

**Comment by Dinkar850** [comment]
@iamrahulmahato I have resolved it, please check

**Comment by Dinkar850** [comment]
@iamrahulmahato please merge this everyday i have to clear conflicts

**Pull request merged**
