### PR TITLE
Responsive Fractal Generator

### PR DESCRIPTION
**Pull request by shriyadindi**
I've made the new project Responsive Fractal Generator.
issue no. : #1733 

https://github.com/user-attachments/assets/e3a42248-cc5b-4a4e-8a7c-9338369d7e9f

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@shriyadindi resolve the conflict

**Comment by shriyadindi** [comment]
@iamrahulmahato Done!

**Comment by iamrahulmahato** [comment]
@shriyadindi conflict is there

**Comment by shriyadindi** [comment]
@iamrahulmahato I've tried resolving the conflict, please look at it.

**Pull request merged**
