### PR TITLE
Added the word scramble game

### PR DESCRIPTION
**Pull request by Vijitverm1234**
I have just added word scramble game which contain fresh 20 scramble words related to web development 
scramble
Here with a special description 
now the preview of the project is as follow 
scramble1

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
solved the conflict. And then try to push.

**Comment by Vijitverm1234** [comment]
i have checked it , there is no conflict that's just only updates @iamrahulmahato  please check

**Comment by Vijitverm1234** [comment]
chaos
this must be there to show the game why this is considered as conflict 😵‍💫🥹

**Comment by iamrahulmahato** [comment]
Web capture_6-10-2024_214746_github com

**Comment by Vijitverm1234** [comment]
I am trying to resolve it . can you please suggest me how to 🥹

**Comment by Vijitverm1234** [comment]
done .. please check

**Comment by iamrahulmahato** [comment]
not solved

**Comment by Vijitverm1234** [comment]
please check

**Comment by iamrahulmahato** [comment]
@Vijitverm1234 there is a conflict

**Comment by iamrahulmahato** [comment]
@Vijitverm1234 if you are getting issue please update the fork then add your code then make a pr request

**Comment by iamrahulmahato** [comment]
i am closing the as its been more than the 2 week please make a new pr

**Pull request closed without merging**
