### PR TITLE
Weather and Outfit Recommender

### PR DESCRIPTION
**Pull request by shriyadindi**
I've added a new project Weather and Outfit Recommender.
issue no. : #1723

https://github.com/user-attachments/assets/711de054-a107-4ce2-8946-8e283d562c44

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@shriyadindi resolve the conflict

**Comment by shriyadindi** [comment]
@iamrahulmahato Resolved the conflict!
Please do add the gssoc, hacktoberfest and the level badge.

**Comment by iamrahulmahato** [comment]
@shriyadindi not solved

**Comment by shriyadindi** [comment]
@iamrahulmahato Resolved the conflict!
Please do add the gssoc, hacktoberfest and the level badge.

**Comment by iamrahulmahato** [comment]
@shriyadindi not solved

**Comment by shriyadindi** [comment]
@iamrahulmahato Done!

**Pull request merged**
