### PR TITLE
Guess the country game added

### PR DESCRIPTION
**Pull request by TBorundia**
Issue: #544
Added Guess the country game to the website.

image

It is responsive too for all screen sizes.

image

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
there is a conflict; resolve it

**Comment by iamrahulmahato** [comment]
conflict not solved

**Comment by TBorundia** [comment]
@iamrahulmahato , Resolved the conflicts.
Please review it now!!

**Comment by TBorundia** [comment]
@iamrahulmahato , Please review it now

**Pull request merged**
