### PR TITLE
chore(duplicates-cards): removed duplicate cards

### PR DESCRIPTION
**Pull request by Sandigupta**
- Removed duplicate cards

### CODE REVIEW

**Comment by Sandigupta** [comment]
@iamrahulmahato  I am resolved the conflict. Please merge the PR: )

**Comment by Sandigupta** [comment]
@iamrahulmahato  Please go with the merge else we are going to have lots of conflict.
Thanks.

**Comment by Sandigupta** [comment]
taking a long time.

**Comment by Sandigupta** [comment]
Okay, I am doing it.

**Comment by Sandigupta** [comment]
Hey @iamrahulmahato, can you please merge it? Since there are too many changes, we will get lots of conflict if you not merge it before any other pr.

Thank you.

**Comment by Sandigupta** [comment]
Build is getting failed because there is one submodule but there is no reference for sub-modules. There might be some PR that got merged with sub-modules. Please check. 
image

**Comment by Sandigupta** [comment]
Please merge it . I removed all duplicate cards.

**Comment by Sandigupta** [comment]
@iamrahulmahato 
removed duplicate cards #1043

**Comment by Sandigupta** [comment]
@iamrahulmahato 
chore(duplicates-cards): removed duplicate cards #1043

**Comment by Sandigupta** [comment]
@iamrahulmahato Please merge this PR.

**Comment by iamrahulmahato** [comment]
mention the issue no, where i assigned you the task

**Comment by Sandigupta** [comment]
This is the issue number: :#1043
 chore(duplicates-cards): removed duplicate cards #1043

**Comment by iamrahulmahato** [comment]
closing this issue its been 2 week please make a new pr

**Pull request closed without merging**
