### PR TITLE
Added Random movie Name generator

### LINKED ISSUE #1692: 📃: Can Add Random Movie name generator.
🔴 Title :Random Movie name generator.
Here is an example filled out with the requested information:
🔴 Tech Stack:
Frontend: HTML, CSS,python
Version Control: Git
🔴 Objective:
Develop a simple web application to display random movie names with Flask as the backend and a minimalistic user interface using HTML and CSS.
🔴 Summary:
This project is a basic web application that generates and displays a random movie name each time the page is refreshed. It uses  simple HTML/CSS for the frontend.
📸 Screenshots:
N/A
✅ Details to Include When Taking the Issue:
Name: pooja k
Participant Role: Contributor

Hacktoberfest 2024

Happy Contributing! 🚀 @iamrahulmahato kindly assign the work to me

Wishing you all the best on your open source journey. Enjoy! 😎

### PR DESCRIPTION
**Pull request by PoojaKanagaraj06**
Fixes #1692 @iamrahulmahato I have added random movie name generator 
**Before**
image

**After**
image
image

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@PoojaKanagaraj06 resolve the conflict

**Comment by iamrahulmahato** [comment]
@PoojaKanagaraj06 not solved

**Comment by iamrahulmahato** [comment]
@PoojaKanagaraj06 if you are getting issue please update the fork then add your code then make a pr request

**Comment by PoojaKanagaraj06** [comment]
@iamrahulmahato okay

**Comment by PoojaKanagaraj06** [comment]
@iamrahulmahato corrected merge conflicts

**Pull request merged**
