### PR TITLE
removed duplicate minesweeper game

### PR DESCRIPTION
**Pull request by Sandigupta**
Please merge this PR.
thanks

### CODE REVIEW

**Comment by Sandigupta** [comment]
issue number

🐞 : Duplicate minesweeper card. #1260

**Comment by Sandigupta** [comment]
Please merge this PR.
thanks

**Comment by iamrahulmahato** [comment]
conflict is not resolved

**Comment by Sandigupta** [comment]
All conflicts are resolved.
Please merge this PR.
thanks

**Comment by Sandigupta** [comment]
@iamrahulmahato Please merge this PR.

**Comment by Sandigupta** [comment]
@iamrahulmahato please merge this PR.

**Comment by iamrahulmahato** [comment]
buddy there are still some conflict and some checks are also failed

**Comment by Sandigupta** [comment]
@iamrahulmahato In order to avoid another conflict, please merge this PR.
thanks

**Comment by Sandigupta** [comment]
@iamrahulmahato 
Please merge this.

**Comment by iamrahulmahato** [comment]
mention the issue no and please update the fork and make changes then make the pr request

**Comment by Sandigupta** [comment]
issue no. #1260
Please merge this pr

**Comment by Sandigupta** [comment]
@iamrahulmahato 
issue no. https://github.com/iamrahulmahato/master-web-development/issues/1260
Please merge this PR.

**Comment by iamrahulmahato** [comment]
Web capture_25-10-2024_152430_github com
man i am doing one thing. i am deleteing this pr as its is not updated. thats way conflict is coming so please update the fork and make changes, then make the pr request

**Pull request closed without merging**
