### PR TITLE
Travel destination generator

### PR DESCRIPTION
**Pull request by shriyadindi**
I've added a new project Travel destination generator.
issue no. : #1732 

https://github.com/user-attachments/assets/70326550-caf6-4754-bc64-27b7757036fd

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@shriyadindi resolve the conflict

**Comment by shriyadindi** [comment]
@iamrahulmahato Done!

**Comment by iamrahulmahato** [comment]
@shriyadindi not done

**Comment by shriyadindi** [comment]
@iamrahulmahato I've tried resolving the conflict, please look at it.

**Pull request merged**
