### PR TITLE
Sucessfully added Simon -Says (Advances Version) game #445

### PR DESCRIPTION
**Pull request by yeshwanth-ds**
# Simon Says (Advanced Version) Game

## Project Overview
This project involves the development of an **Advanced Version** of the classic Simon Says memory game. The game challenges players to recall and replicate sequences of colors, with difficulty increasing as they progress through levels. This version provides a highly interactive experience through visual and audio feedback, score tracking, and level progression.

## Task Overview
This task involved creating the **Simon Says Advanced Version** game and merging it with the main branch as part of the development process. Below is a summary of the completed task:

- **Branch Created**: `simon-says`
- **Task Completed**: Developed a Simon Says game, tested it thoroughly, and successfully merged it into the main branch.
- **Commit Details**: All changes were committed and pushed successfully.
- **Pull Request Details**: This PR includes the fully functioning Simon Says game integrated into the project.
- **Issue Number**: #445

## Game Features
- **Enhanced Memory Challenge**: Players must remember progressively longer and more intricate sequences of colors.
- **Visual and Audio Feedback**: Each color is accompanied by a sound and visual cue, enhancing the immersive experience.
- **Level Progression**: Difficulty increases as players successfully complete each level, introducing longer sequences.
- **Score Tracking**: Points are awarded based on player performance, with levels contributing to the score.

## Tech Stack
- **HTML5**: Structured the game layout with buttons and display elements.
- **CSS3**: Styled the interface with responsive design, including animations for button interactions.
- **JavaScript (ES6)**: Implemented game logic, user interaction, and sound effects for game interactivity.

## Task Completion
- [x] Created `simon-says` branch
- [x] Completed Simon Says game development
- [x] Linked and merged with the main branch
- [x] Submitted pull request for review

## Tags for Admin Consideration
Please make sure the following tags are allocated to this PR:

- **gihacktoberfest**
- **hacktoberfest-accepted**
- **level3**
- **gssoc-ext**

## How to Play
1. **Start the Game**: Click the "Start Game" button to begin.
2. **Follow the Pattern**: The game will show a sequence of colors that you must replicate by clicking the corresponding buttons.
3. **Increase Difficulty**: Each level will add one more color to the sequence, increasing the difficulty.
4. **Scoring**: Earn points for every correct sequence. Try to achieve the highest score!

## Task Completion Video

https://github.com/user-attachments/assets/dd160f3a-ea0f-4818-93e3-bbf35d544a40

Thank you for reviewing this pull request. I look forward to your feedback and approval.

### CODE REVIEW

**Comment by yeshwanth-ds** [comment]
# Bubble Shooter Game Development

## Task Overview

This task involved creating a **Bubble Shooter** game from scratch and linking it to the main branch as part of the development process for issue no. **#446**. Below is a brief summary of the completed task:

- **Branch Created**: `bubble-shooter`
- **Task Completed**: Developed a Bubble Shooter game and merged it with the main branch after thorough testing.
- **Commit Details**: All changes were committed and successfully pushed.
- **Pull Request Details**: This PR includes the fully functioning Bubble Shooter game integrated into the project.

## Features of the Bubble Shooter Game
- **Canvas-based gameplay** using JavaScript and HTML5.
- Players can **shoot bubbles** from a cannon, aiming to match three or more bubbles of the same color.
- **Grid-based system** with collision detection to snap bubbles into place and check for matches.
- **Score updates** automatically as bubbles are popped.
- Dynamic game environment where **bubbles fall** when matching sets are removed.
- Fully responsive for **desktop browsers**.

## Tags for Admin Consideration
Please make sure the following tags are allocated to this PR:
- `gihacktoberfest`
- `hacktoberfest-accepted`
- `level3`
- `gssoc-ext`

## Task Completion Video

https://github.com/user-attachments/assets/a91c04d6-ed1f-4e42-8223-8f0d73df6757


Thank you for reviewing this pull request. I look forward to your feedback and approval.

---

## Checklist:

- [x] Created `bubble-shooter` branch
- [x] Completed Bubble Shooter game development
- [x] Linked and merged with the main branch
- [x] Submitted pull request for review for this project

**Comment by yeshwanth-ds** [comment]
@iamrahulmahato In this PR i have added two project i.e Simon-Says(Advanced Version) and Shooter Game. I hope that doe not affect in assigning the PR label Tags seperately.

**Comment by iamrahulmahato** [comment]
i am closing it make a new pr for this with the issue no

**Comment by yeshwanth-ds** [comment]
@iamrahulmahato The thing is i mad two pull request one after another and due to that both the PR apper. When I went to raise the PR the both the coomits are still together i.e the projrcts. I solved this over night to reduce confilts. Help me nagivate through .

**Pull request closed without merging**
