### PR TITLE
AddedPokedex

### PR DESCRIPTION
**Pull request by jjf2009**
Issue #89 
Added the Pokedex 
Screenshot:
Screenshot 2024-10-02 065835

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
there is a conflict resolve it

**Comment by jjf2009** [comment]
Conflict is resolved

**Comment by iamrahulmahato** [comment]
not solved

**Comment by jjf2009** [comment]
@iamrahulmahato check now

**Comment by jjf2009** [comment]
@iamrahulmahato  please add gssoc-ext , hacktobter-accepted and level 3 same as the labels i the issue . Please

**Pull request merged**
