### PR TITLE
Sudoku webapplication

### PR DESCRIPTION
**Pull request by saurabhsagar99**
Added the code for sudoku game

### CODE REVIEW

**Comment by Tapabrata-Goswami** [comment]
Hi, @saurabhsagar99 check your request have some conflicts.

**Comment by saurabhsagar99** [comment]
conflict has been resolved

**Comment by Tapabrata-Goswami** [comment]
@saurabhsagar99 check your out put

image

https://deploy-preview-235--master-web-development.netlify.app/
scroll to bottom check the out put

**Comment by saurabhsagar99** [comment]
@Tapabrata-Goswami resolved

**Comment by saurabhsagar99** [comment]
@Tapabrata-Goswami I have resolved all the issue so can you merge my pr

**Comment by iamrahulmahato** [comment]
there is a conflict

**Comment by saurabhsagar99** [comment]
@iamrahulmahato conflict has been resolved

**Pull request merged**
