### PR TITLE
Added Word counter app #Issue264

### PR DESCRIPTION
**Pull request by prasoonk1204**
## Added a word counter app which counts words, characters, gives the reading time, and many other things.
_also added the app's card in main index.html file_

Screenshot 2024-10-04 010943
screencapture-127-0-0-1-5500-projects-Word-counter-index-html-2024-10-04-01_38_27

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by iamrahulmahato** [comment]
there is a conflict

**Comment by prasoonk1204** [comment]
I'll resolve it by evening

**Comment by prasoonk1204** [comment]
I have resolved the conflict.

You can add this code in the landing page to link it to word counter app

`<a href="./projects/Word-counter/index.html" class="card">
             <div class="card-cover">
                    word counter
                </div>
                <div class="card-content">
                    <h3 class="card-heading">Word Counter</h3>
                    <p class="card-description">
                       Simple tool for counting words and characters.
                    </p>
                </div>
            </a>`

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by prasoonk1204** [comment]
Issue no. #264

**Pull request merged**
