### PR TITLE
Add 2048 Game

### PR DESCRIPTION
**Pull request by meghanakn473**
This pull request adds a fully functional 2048 game to the master-web-development repository. It features dynamic tile movement and merging based on keyboard input, along with score tracking that updates as tiles combine. The user interface has been enhanced for better visual appeal, including CSS styling for the game grid and tiles. Players can aim to reach the 2048 tile by using the arrow keys to slide and merge tiles. Future improvements may include win/lose notifications and audio effects.

Screenshot (137)

Screenshot (138)

### CODE REVIEW

**Comment by meghanakn473** [comment]
Also created Community Forum

This pull request introduces the initial implementation of a community forum feature in the application, allowing users to create posts, comment on discussions, and engage with fellow community members. The implementation includes routes for creating, retrieving, updating, and deleting forum posts, along with a Mongoose model for posts that captures the title, content, author, and timestamps. Additionally, controllers have been created to handle the forum logic, and front-end components have been set up to display posts and manage user interactions. Testing has confirmed that users can successfully create and view posts, with robust error handling in place. Future enhancements may include user profiles, notifications for new comments, and improved moderation tools.

**Comment by meghanakn473** [comment]
@iamrahulmahato  could you please review this PR and allow merge request?

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by meghanakn473** [comment]
> mention the issue no

sorry i didnt get you, can you be more clear? did u mean to mention the issue number? or wt is the issue about?

**Comment by meghanakn473** [comment]
> mention the issue no

th issue is about : adding 2048 game 
and the issue number is : #65

**Pull request merged**
