### PR TITLE
Modified Homepage

### PR DESCRIPTION
**Pull request by SumaLatha2023**
Misplaced and Unnecessary Duplicate Images on Home Page

Issue no. #1698 was solved

### CODE REVIEW

**Comment by SumaLatha2023** [comment]
## Before
Screenshot 2024-10-24 192922

## After
Screenshot 2024-10-28 151700

**Comment by iamrahulmahato** [comment]
@SumaLatha2023 resolve the conflicts

**Comment by iamrahulmahato** [comment]
@SumaLatha2023 resolve the conflict

**Comment by SumaLatha2023** [comment]
@iamrahulmahato I have deleted index file by mistake, how can I undo the commit .. can u tell ?

**Comment by iamrahulmahato** [comment]
you can pull that

**Comment by iamrahulmahato** [comment]
However, I am closing it for the best, the update he fork, add your code, and creating a PR after that.

**Pull request closed without merging**
