### PR TITLE
Interactive Storybook with Branching Paths✨

### PR DESCRIPTION
**Pull request by shriyadindi**
I've added a new project named Interactive Storybook with Branching Paths.
issue no. : #1689 

https://github.com/user-attachments/assets/04bf64fe-a8a3-4cda-afc9-4b8f4f86557c

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@shriyadindi resolve the conflict

**Comment by shriyadindi** [comment]
@iamrahulmahato Resolved the conflict!

**Comment by iamrahulmahato** [comment]
@shriyadindi not solved

**Comment by shriyadindi** [comment]
@iamrahulmahato Resolved the conflict!
Please do add the gssoc, hacktoberfest and the level badge.

**Pull request merged**
