### PR TITLE
Sucessfully added Tetris game #444 

### PR DESCRIPTION
**Pull request by yeshwanth-ds**
# Tetris Game Task Completion

## Task Overview
This task involved creating a Tetris game and linking it to the main branch as part of the development process. Below is a brief summary of the completed task:

- **Branch Created:** `tetris`
- **Task Completed:** Developed a Tetris game and merged it with the main branch after thorough testing.
- **Commit Details:** All changes were committed and successfully pushed.
- **Pull Request Details:** This PR includes the fully functioning Tetris game integrated into the project.

## Tags for Admin Consideration
Please make sure the following tags are allocated to this PR:

- `gihacktoberfest`
- `hacktoberfest-accepted`
- `level3`
- `gssoc-ext`

## Task Completion Video

Thank you for reviewing this pull request. I look forward to your feedback and approval.

---

### Checklist:
- [x] Created Tetris branch
- [x] Completed Tetris game development
- [x] Linked and merged with the main branch
- [x] Submitted pull request for review

### CODE REVIEW

**Comment by yeshwanth-ds** [comment]
**TASK COMPLETION VIDEO**


https://github.com/user-attachments/assets/e99632c6-28db-4dda-911f-0207f8f72361

**Comment by yeshwanth-ds** [comment]
**TASK COMPLETION VIDEO**

https://github.com/user-attachments/assets/e99632c6-28db-4dda-911f-0207f8f72361

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by yeshwanth-ds** [comment]
@iamrahulmahato #444

**Pull request merged**
