### PR TITLE
Real-Time Heatmap with Mouse Interactions (Issue #1864)

### PR DESCRIPTION
**Pull request by shriyadindi**
Real-Time Heatmap with Mouse Interactions 
Issue : #1864 

https://github.com/user-attachments/assets/908652f4-0afe-4631-9e1d-44f9b1d0b4e3

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@shriyadindi there is a conflict

**Comment by shriyadindi** [comment]
@iamrahulmahato resolved

**Comment by iamrahulmahato** [comment]
@shriyadindi I must address something with you: there is a 200-point limit for each person in this repository, and your points are so high that I am unable to grant further any level to you.

**Comment by shriyadindi** [comment]
Can you please give me the points to the pull requests that I've done till now, I'll not raise an issue further more. 
It has taken a lot of time and effort to make each project, please understand my situation

**Comment by iamrahulmahato** [comment]
@shriyadindi I am not adding it because I am aware that even if I give at the end, your points will be disqualified.

**Comment by iamrahulmahato** [comment]
I cant change  the rule and i have responsibility you need to understand Additionally, it mentions that about 20 days ago, https://github.com/iamrahulmahato/master-web-development/issues/140, and I also pined it.
As stated on the official gssoc website, https://docs.google.com/spreadsheets/d/116FmD6qpoAE53hEATtu2OPnU3G3ZvMt5PFrVOy6Wt3Y/edit?gid=0#gid=0 and in gg

**Comment by iamrahulmahato** [comment]
No, there isn't, so now I have to end all of your PRs with nolevel.

**Comment by shriyadindi** [comment]
@iamrahulmahato can you please add a level 1 for now, its okay if they disqualify my points later, please.

**Comment by shriyadindi** [comment]
@iamrahulmahato please dont do that, the only help I'm asking is to add the level 1 to the prs that I've done till now, I'll not raise an issue again, I've worked very hard for each of the project as I was unaware of the limit.

**Pull request merged**
