### PR TITLE
Gradient link fixed

### LINKED ISSUE #108: Fix broken link on "Generate Gradient" card
When users click on the "Generate Gradient" card, the linked page either shows an error or fails to load correctly. This impacts the user experience, as the feature doesn't work as intended. I would love to help fix this issue. I can review the link associated with the card, correct the URL, and ensure it directs to the right page or a placeholder. Additionally, I’d be happy to fix the typo in the card description from "radom" to "random."
photo_2024-10-02_02-25-55
photo_2024-10-02_02-26-22

### PR DESCRIPTION
**Pull request by jjf2009**
Fixed #108 
Kindly added the labels before merging 
Video :-
[screen-recorder-wed-oct-02-2024-09-51-54.webm](https://github.com/user-attachments/assets/c43acf24-bda8-4849-b831-dfbf364414a9)

### CODE REVIEW

**Comment by jjf2009** [comment]
Can u tell me what need to be done to get checks passed

**Comment by iamrahulmahato** [comment]
When submitting a pull request, please also include a screenshot or preview.

**Comment by jjf2009** [comment]
> When submitting a pull request, please also include a screenshot or preview.

i have added a video

**Comment by vansh-codes-dev** [comment]
Hii @iamrahulmahato 
Please check the issues mentioned once before merging the PRs, in this case its someone else's issue which he has worked upon without being assigned, in such cases notify the contributor to first get the issue assigned and then create PR
you can close this PR and assign the one who created the issue
-GSSOC Team

**Comment by vansh-codes-dev** [comment]
@jjf2009 You first have to get the issue assigned to yourself, you cant work on someone else issue until and unless assigned to you, if you continue to do so, your points will be deducted and you might get flagged inappropriate
-GSSOC Team

**Comment by jjf2009** [comment]
> @jjf2009 You first have to get the issue assigned to yourself, you cant work on someone else issue until and unless assigned to you, if you continue to do so, your points will be deducted and you might get flagged inappropriate -GSSOC Team

ok

**Pull request closed without merging**
