### PR TITLE
#145 updated counter application

### PR DESCRIPTION
**Pull request by Blessy-B-Sherin**
https://github.com/user-attachments/assets/2dd4e2d0-b5df-4f65-8f6d-80fac34c9d6e

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by Blessy-B-Sherin** [comment]
> mention the issue no
Issue No: #145....Improve the Counter Game with Additional Features and Code Optimization #145

**Comment by iamrahulmahato** [comment]
there is a conflict; resolve it

**Comment by Blessy-B-Sherin** [comment]
> there is a conflict; resolve it

resolved it

**Pull request merged**
