### PR TITLE
Simon says game

### PR DESCRIPTION
**Pull request by Sharibraza**
🔴 Title :   Simon says game.

🔴 Tech stack : HTML, CSS, JavaScript.

🔴 Objective :  The objective of the "Simon Says" color game is to remember and repeat sequences of colors shown on the screen. The goal is to accurately follow the pattern without making mistakes, improving memory and attention skills in a fun and engaging way. 

🔴 Summary:  This version of the "Simon Says" game presents a colorful 2x2 grid of squares: green, red, yellow, and blue. The game starts with the prompt "Press any key to start." Players need to remember and replicate sequences of colors and sounds generated by the game. It's a fun test of memory and attention! Ready to play?

📸 Screenshots: 
Screenshot 2024-10-08 220812

Name : Sharibraza.

Please add this to GSSOC, Hacktoberfest-Extd.

### CODE REVIEW

**Comment by Sharibraza** [comment]
Please add this to GSSOC, Hacktoberfest-Extd.

**Comment by iamrahulmahato** [comment]
mention the issue no?

**Comment by Sharibraza** [comment]
> mention the issue no?
#832

**Comment by iamrahulmahato** [comment]
issue no, where i assigned you the task?

**Comment by iamrahulmahato** [comment]
I am closing this request since you have not been given this task.

**Pull request closed without merging**
