### PR TITLE
Add Visitor Counter feature done ! #1586 ✨✨

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #1586
Add Visitor Counter feature done properly -

Screenshot 2024-10-27 153104

Before -

Screenshot 2024-10-27 153112

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato

**Comment by iamrahulmahato** [comment]
@Subhajit-2023-44 there is a conflict resolve it

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 there is a conflict resolve it

@iamrahulmahato done

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato sir kindly upgrade the level 1 to 3..

level 1 is too low for this..

**Pull request merged**
