### PR TITLE
Bubble shot game

### PR DESCRIPTION
**Pull request by rajnil9**
A simple Bubble shot game

Gameplay:  Click on the bubbles to pop them and increase your score.

Graphics: The game uses simple shapes for bubbles.

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@rajnil9  mention the issue no

**Comment by rajnil9** [comment]
@iamrahulmahato  issue no. #2321

**Comment by rajnil9** [comment]
I have added the issue no. please check github pull request comment section

**Comment by aslams2020** [comment]
@rajnil9 You were not assigned to work on it. This PR cannot be merged

**Comment by rajnil9** [comment]
assign me this please @iamrahulmahato

**Pull request closed without merging**
