### PR TITLE
added github profile viewer

### PR DESCRIPTION
**Pull request by adityalaxkar123**
#people can see their profile photo,follower,following and repository

### CODE REVIEW

**Comment by adityalaxkar123** [comment]
my issue no. is #234

**Comment by Tapabrata-Goswami** [comment]
@adityalaxkar123 I think you worked on the wrong folder

**Comment by adityalaxkar123** [comment]
mean but the deployment preview is working

**Comment by adityalaxkar123** [comment]
Screenshot (965)
but deployment preview is working. i do similar to another person

**Comment by adityalaxkar123** [comment]
i don't know what mistake i did it. can you explain it to me

**Pull request closed without merging**
