### PR TITLE
Kept it to the sidebar

### PR DESCRIPTION
**Pull request by HimangshuSharma01**
image

made the changes 
Isuue #1833

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@HimangshuSharma01 mention the issue no

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 mention the issue no

done

**Comment by HimangshuSharma01** [comment]
@iamrahulmahato why no level?

**Comment by HimangshuSharma01** [comment]
the issue was of level 1

**Comment by HimangshuSharma01** [comment]
@iamrahulmahato  please add level 1

**Comment by HimangshuSharma01** [comment]
@iamrahulmahato  add level 1 it was level 1 in the issue thats why i did this

**Pull request merged**
