### PR TITLE
Cricket Game

### PR DESCRIPTION
**Pull request by rajnil9**
I have added a cricket game using html , css , javascript .
Game Description :
Score: You accumulate runs by clicking the "Hit the Ball!" button.
Outcome: Each click randomly generates a score between 0 to 6. If the score is 0, a message will indicate that you've been "Out".

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@rajnil9 mention the issue no

**Comment by rajnil9** [comment]
@iamrahulmahato issue no. #2322

**Comment by rajnil9** [comment]
I have added the issue no. please check github pull request comment section

**Comment by rajnil9** [comment]
assign me this please @iamrahulmahato

**Pull request merged**
