### PR TITLE
CHANGED THE LOOK OF THE WEBSITE ALSO ADDED A FEATURE OF ENTER KEY IS CHECK NOW. 
ISSUE #128

### PR DESCRIPTION
**Pull request by HS202022**
The website's appearance was updated with a custom background image and gradient for a fresh look, and the container now has a semi-transparent background. Additionally, a feature was added to allow the "Enter" key to trigger the "Check Now" button automatically, improving user experience.

### CODE REVIEW

**Comment by HS202022** [comment]
Screenshot 2024-10-02 083001

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by HS202022** [comment]
> mention the issue no

Actually I'm new to this would you please tell me how to mention that and where to mention

**Comment by iamrahulmahato** [comment]
To make a pull request, first go to the issue tab and raise the issue that you want to add and/or change any existing issues in the project. Once assigned, make changes to the project and make the pull request.

**Comment by iamrahulmahato** [comment]
issue no?

**Comment by HS202022** [comment]
#128> issue no?

**Pull request merged**
