### PR TITLE
Add Translation Tool done ! #1457

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Fixed issue - #1457
Add new feature - Translation Tool

https://github.com/user-attachments/assets/0126e848-1905-43d6-8279-532690fbbeee

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato sir merge my PR with level 3

If you check other projects, they are giving level 3 for this ,.

Screenshot 2024-10-19 130956

Thank You 🙏🏻

**Comment by iamrahulmahato** [comment]
yes they can but in repo there are some restrictions that i can give you max 200 points and max 2 levels

**Comment by Subhajit-2023-44** [comment]
> yes they can but in repo there are some restrictions that i can give you max 200 points and max 2 levels

@iamrahulmahato then give me at least level 2 😭😭

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato

**Pull request merged**
