### PR TITLE
Add a User Profiles page done ! #2019

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #2019
Add a normal user profile page and a profile icon in the home page that redirects to the profile page done -

https://github.com/user-attachments/assets/a6cc35be-bf05-4597-b6ad-5466a5606972

Screenshot 2024-11-03 085605

Screenshot 2024-11-03 085611

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@iamrahulmahato done, merge my PR & please give me level 3, you can check my code i have added a lot.. 🌟🌟🌟

image

**Comment by iamrahulmahato** [comment]
fix #2019

**Comment by iamrahulmahato** [comment]
@Subhajit-2023-44 I can only give max 2 levels. There is  a restriction in this repo Read the guidelines

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 I can only give max 2 levels. There is a restriction in this repo Read the guidelines

Okay

**Pull request merged**
