### PR TITLE
Ping Pong Game

### PR DESCRIPTION
**Pull request by rajnil9**
Gameplay: Move your paddle using the mouse to hit the ball back to the computer. The computer paddle moves automatically.
Scoring: Points are awarded when the opponent fails to hit the ball.
Visuals: The game features a simple design with a dark background and white elements for contrast.

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@rajnil9  mention the issue no

**Comment by rajnil9** [comment]
@iamrahulmahato issue no. #2319

**Comment by rajnil9** [comment]
I have added the issue no. please check github pull request comment section

**Comment by rajnil9** [comment]
assign me this please @iamrahulmahato

**Pull request closed without merging**
