### PR TITLE
<Gesture via voume control>

### PR DESCRIPTION
**Pull request by eshalshaikh07**
As a contributor to the Hand Gesture Volume Control project, I developed a Python application that utilizes computer vision techniques to control system volume through hand gestures. This project leverages OpenCV and MediaPipe for real-time hand tracking, enabling users to adjust audio levels seamlessly through natural hand movements.

Key Contributions:
Real-time Hand Gesture Recognition: Implemented a robust hand detection system using MediaPipe, allowing for accurate tracking of hand positions and movements.
Dynamic Volume Control Logic: Developed a volume adjustment algorithm that translates the position of the user's hand into corresponding system volume levels, enabling smooth transitions from 0 to 100%.
Distance-Based Volume Adjustment: Designed a system where the height of the user's hand correlates with the volume level, allowing users to easily increase or decrease volume by raising or lowering their hand.
Cross-Platform Compatibility: Ensured the application operates effectively across various operating systems, making it accessible for a wide range of users.
Technologies Used:
Python
OpenCV
MediaPipe
Pycaw (for system volume control)
This project demonstrates the potential of gesture-based interfaces in enhancing user interaction with technology, providing an intuitive solution for audio control without physical contact. I am excited to contribute to an open-source initiative that merges innovative computer vision with practical applications, improving accessibility and user experience.

https://github.com/user-attachments/assets/0443a2a3-f85a-4a5a-b184-8f07d5a863a6

look at the sound settings change according to hand movement.

### CODE REVIEW

**Comment by eshalshaikh07** [comment]
Hope you like it!

**Comment by iamrahulmahato** [comment]
mention the issue no?

**Comment by eshalshaikh07** [comment]
574

**Comment by eshalshaikh07** [comment]
issue 574
please check

**Comment by eshalshaikh07** [comment]
> fix #574

Hey!!! I didn't received my score for this.

**Comment by eshalshaikh07** [comment]
> mention the issue no?

Hey what about my score!

**Pull request merged**
