### PR TITLE
Random Image Generator

### PR DESCRIPTION
**Pull request by rajnil9**
Random Image Generation: When you click the "Generate Image" button, a random image from the predefined list will be displayed.
Image Display: The images will be visible below the button once generated.

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@rajnil9  mention the issue no

**Comment by rajnil9** [comment]
@iamrahulmahato  issue no. #2320

**Comment by rajnil9** [comment]
I have added the issue no. please check github pull request comment section

**Comment by rajnil9** [comment]
assign me this please @iamrahulmahato

**Pull request closed without merging**
