### PR TITLE
Added follow us section

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
#1753 
Added follow us section with linkedin,github,twitter with icons and color changing effect after clicking on icon

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
mention the issue no? and resolve the conflict

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
conflicts resolved

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
conflicts resolved ,issue #1753

**Comment by iamrahulmahato** [comment]
@KapuluruBhuvaneswariVspdbct not solved

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@iamrahulmahato  kindly check once sir

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
can you add level2 label please if possible @iamrahulmahato

**Pull request merged**
