### PR TITLE
Footer CSS fixed

### PR DESCRIPTION
**Pull request by ChampGupta**
The footer part of the website is improved along with other anchor tag with empty link is also added for future updation(delete or comment out if not required)
Screenshot 2024-10-14 at 7 57 24 PM

### CODE REVIEW

**Comment by ChampGupta** [comment]
Issue number #1122

**Comment by ChampGupta** [comment]
Please merge the code asap.

**Comment by iamrahulmahato** [comment]
conflict is not resolved

**Comment by ChampGupta** [comment]
@iamrahulmahato conflicts are resolved.

**Comment by ChampGupta** [comment]
@iamrahulmahato please merge the code for issue #1122 ASAP as I have resolved the conflicts.

**Comment by ChampGupta** [comment]
@iamrahulmahato all conflicts have been resolved.
Screenshot 2024-10-18 at 10 04 24 PM

**Pull request merged**
