### PR TITLE
Added Add Multiplayer Option in Tic Tae Toc Game

### PR DESCRIPTION
**Pull request by 13Sharad**
#1691

### CODE REVIEW

**Comment by 13Sharad** [comment]
@iamrahulmahato please merge this pull request.

**Comment by 13Sharad** [comment]
@iamrahulmahato please merge this pull request.

**Comment by 13Sharad** [comment]
@iamrahulmahato please merge this pull request.

**Comment by 13Sharad** [comment]
@iamrahulmahato please merge this pull request.

**Comment by 13Sharad** [comment]
@iamrahulmahato please merge this pull request.

**Comment by 13Sharad** [comment]
@iamrahulmahato please merge this pull request.

**Comment by iamrahulmahato** [comment]
@13Sharad resolve the conflict

**Comment by 13Sharad** [comment]
@iamrahulmahato  i remove the conflict.

**Pull request merged**
