### PR TITLE
My new version of Snake

### PR DESCRIPTION
**Pull request by t1nt1n-s0lv3r**
I have updated the snake game with score and high score with more UI design and implemented a separate snake head and body and an apple has been implemented into the snake project

@iamrahulmahato im facing issues with the branch conflicts i created my own Snake Game could you help me with resolving this please

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
Mention the issue number and resolve the conflict.

**Comment by t1nt1n-s0lv3r** [comment]
The issue no is #55 
and the conflicts im facing is i have created my own index.html , style.css and script.js
image

**Comment by iamrahulmahato** [comment]
conflict is not solved

**Comment by iamrahulmahato** [comment]
try closing this pr and make a new pr

**Pull request closed without merging**
