### PR TITLE
Added Guess the shape

### PR DESCRIPTION
**Pull request by TBorundia**
Issue: #543 
Added Guess the shape with the help of discription

image

image

### CODE REVIEW

**Comment by TBorundia** [comment]
@iamrahulmahato , Please review this PR.
Can you label it with level 2 for my work. Thank You!!

**Comment by TBorundia** [comment]
@iamrahulmahato , Solved the conflicts. Please review it !!

**Comment by iamrahulmahato** [comment]
Web capture_19-10-2024_102323_github com
Web capture_19-10-2024_10238_github com
this are the conflict

**Comment by TBorundia** [comment]
@iamrahulmahato ,Solved the conflicts.
 Please review it . Can you label it with level 2 for my work.
Thank You!!

**Pull request merged**
