### PR TITLE
[FIX] Wordle typo in landing page fixed 

### LINKED ISSUE #281: [BUG] wrong game name in landing page
## Wrong Name in Landing Page
- There is a project called LiveClock.
- And a game named "WORDLE" below the live clock. 
- But there is 2 live clock written mistakenly.

## Screenshot :

image

### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

### PR DESCRIPTION
**Pull request by 4F24L**
## Fixed Wordle Typo in Landing Page
- Fixes #281 
- Wordle game name fixed.

## Screenshot :

image

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
mention the issue no

**Comment by iamrahulmahato** [comment]
there is a conflict

**Comment by 4F24L** [comment]
Trying to solve the conflict soon!

**Comment by 4F24L** [comment]
> mention the issue no
> Issue number is already mentioned above #281

**Comment by 4F24L** [comment]
Now, all set !

Good to go.

**Comment by 4F24L** [comment]
Hey, it's been long time you have not merged this pull request !!

**Pull request merged**
